//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
// 
namespace TestConfigurationAgent.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConfigurationServiceSoap", Namespace="http://tempuri.org/")]
    public class ConfigurationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ConfigurationService() {
            this.Url = "http://localhost/ConfigurationData/ConfigurationService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConfiguration", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetConfiguration(string section, string environment) {
            object[] results = this.Invoke("GetConfiguration", new object[] {
                        section,
                        environment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetConfiguration(string section, string environment, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetConfiguration", new object[] {
                        section,
                        environment}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetConfiguration(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
